version: "3"
services:
  mydbSql-Sever:
    image: mysql/mysql-server:5.7
    volumes:
      - v-db-Mysql-PontoInteligente:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ponto_inteligente
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    networks:  
      - network1
volumes:
   v-db-Mysql-PontoInteligente:
networks:
  network1:   